version: "3"
services:
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: codesy
    ports:
      - "5432:5432"
  server:
    image: server
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
  web:
    image: web
    ports:
      - "3000:3000"
  proxy:
    image: abiosoft/caddy:no-stats
    volumes:
      - /root/codesy/Caddyfile:/etc/Caddyfile
      - /root/.caddy:/root/.caddy
      - /root/logs:/etc/logs
      - /root/goaccess/.html:/site/goaccess
    ports:
      - "80:80"
      - "443:443"
      - "7890:7890"
    depends_on:
      - web
      - server
  goaccess:
    image: allinurl/goaccess
    ports:
      - 7890:7890
    volumes:
      - ./goaccess/config:/srv/config
      - ./goaccess/data:/srv/data
      - ./goaccess/html:/srv/report
      - /var/log/nginx:/srv/logs
    command:
      [
        "--no-global-config",
        "--config-file=/srv/config/goaccess.conf",
        "--log-file=/srv/logs/access.log",
      ]
